### ISSUE TITLE
Flex 布局

### ISSUE THREAD

**Issue by Ethanzyc** [Ethanzyc/blog#5]
### Flex 布局

> 准备这篇写详细点，可能会花费一下午，计划赶不上变化啊，开写！
>
> 本文参考了阮一峰老师的[Flex 布局教程：语法篇](http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)和[Flex 布局教程：实例篇](http://www.ruanyifeng.com/blog/2015/07/flex-examples.html)，感谢

#### 注意点：

1. 行内元素也可以使用 Flex 布局。

   ```javascript
   .box{
     display: inline-flex;
   }
   ```

2. Webkit 内核的浏览器，必须加上`-webkit`前缀。

   ```javascript
   .box{
     display: -webkit-flex; /* Safari */
     display: flex;
   }
   ```

3. 设为 Flex 布局以后，子元素的`float`、`clear`和`vertical-align`属性将失效。

***

#### 概念

Flex 布局的英文全称是 **Flexible Box**，中文一般叫弹性盒子模型。

采用了 Flex 的元素称为 Flex 容器`Flex Container`，该元素下面的所有子元素自动成为该容器成员`Flex Item`，也可以称为容器项目。

容器默认存在两根轴：水平的主轴`main axis`和垂直的交叉轴`cross axis`。

***

#### 容器的属性

- flex-direction
- flex-wrap
- flex-flow
- justify-content
- align-items
- align-content

***

先说下本文采用的示例代码，后面的示例会基于这个修改，我会贴出关键部分，box 数量变化之类的就不贴出来了。

```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Flex 布局</title>
    <style>
        .total {
            display: flex;
            flex-direction: row;
        }
        .box {
            font-size: 20px;
            line-height: 100px;
            text-align: center;
            height: 100px;
            width: 100px;
        }
        .box1 {
            background: #333333;
        }
        .box2 {
            background: #555555;
        }
        .box3 {
            background: #777777;
        }
        .box4 {
            background: #999999;
        }
    </style>
</head>
<body>
    <div class="total">
        <div class="box1 box">1</div>
        <div class="box2 box">2</div>
        <div class="box3 box">3</div>
        <div class="box4 box">4</div>
    </div>
</body>
</html>
```

***

##### flex-direction

- `row`（默认值）：主轴为水平方向，起点在左端。
- `row-reverse`：主轴为水平方向，起点在右端。
- `column`：主轴为垂直方向，起点在上沿。
- `column-reverse`：主轴为垂直方向，起点在下沿。

###### row

```css
.total {
    display: flex;
    flex-direction: row;
}
```

![row.png](https://upload-images.jianshu.io/upload_images/11131912-ad01019e1efc39be.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### row-reverse

```css
.total {
    display: flex;
    flex-direction: row-reverse;
}
```

![row-reverse.png](https://upload-images.jianshu.io/upload_images/11131912-ef9e97683010adf0.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### column

```css
.total {
    display: flex;
    flex-direction: column;
}
```

![column.png](https://upload-images.jianshu.io/upload_images/11131912-9b59cc6aca0a7710.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### column-reverse

```css
.total {
    display: flex;
    flex-direction: column-reverse;
}
```

![column-reverse.png](https://upload-images.jianshu.io/upload_images/11131912-71d00dd58ef8dd98.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

***

##### flex-wrap

- `nowrap`（默认）：不换行。元素宽度会被挤压。
- `wrap`：换行，第一行在上方。
- `wrap-reverse`：换行，第一行在下方。

###### nowrap

```css
.total {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
}
```

![nowarp.png](https://upload-images.jianshu.io/upload_images/11131912-d4a03909a871b0cb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### wrap

```css
flex-wrap: wrap;
```

![wrap.png](https://upload-images.jianshu.io/upload_images/11131912-f691a035cfb3a946.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### wrap-severse

```css
flex-wrap: wrap-reverse;
```

![wrap-reverse.png](https://upload-images.jianshu.io/upload_images/11131912-1af25746a521da09.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

***

##### flex-flow

`flex-flow`属性是`flex-direction`属性和`flex-wrap`属性的简写形式，默认值为`row nowrap`。可以将上面两者随意搭配，写起来方便一些。

```css
.total {
    display: flex;
    flex-flow: row wrap;
}
```

***

##### justify-content

`justify-content`属性定义了子元素在主轴上的对齐方式。为了显示效果更好一点，这边我把最外层的背景色换了一下。

- `flex-start`（默认值）：左对齐
- `flex-end`：右对齐
- `center`： 居中
- `space-between`：两端对齐，项目之间的间隔都相等。
- `space-around`：每个项目两侧的间隔相等。所以，项目之间的间隔比项目与边框的间隔大一倍。

###### flex-start

```css
.total {
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
    height: 500px;
    background: #cccccc
}
```

![flex-start.png](https://upload-images.jianshu.io/upload_images/11131912-cfbb5fff987408bc.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### flex-end

```css
justify-content: flex-end;
```

![flex-end.png](https://upload-images.jianshu.io/upload_images/11131912-c282a4abbbca6092.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### center

```css
justify-content: center;
```

![center.png](https://upload-images.jianshu.io/upload_images/11131912-797862d695274935.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### space-between

```css
justify-content: space-between;
```

![space-between.png](https://upload-images.jianshu.io/upload_images/11131912-e6bae6ff1aac5360.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### space-around

```css
justify-content: space-around;
```

![space-around.png](https://upload-images.jianshu.io/upload_images/11131912-bfa2a6e647c7017e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

***

##### align-items

- `flex-start`：交叉轴的起点对齐。
- `flex-end`：交叉轴的终点对齐。
- `center`：交叉轴的中点对齐。
- `baseline`: 项目的第一行文字的基线对齐。
- `stretch`（默认值）：如果项目未设置高度或设为auto，将占满整个容器的高度。

###### flex-start / baseline / stretch （仅在我这个例子中相同，但注意自己的使用场景）

```css
.total {
    display: flex;
    flex-flow: row wrap;
    justify-content: flex-start;
    align-items: flex-start;
    height: 500px;
    background: #cccccc
}
```

![ali-flex-start.png](https://upload-images.jianshu.io/upload_images/11131912-868c53baaeb25930.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### flex-end

```css
align-items: flex-end;
```

![ali-flex-end.png](https://upload-images.jianshu.io/upload_images/11131912-d5855cf0dcce3cef.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### center

```css
align-items: center;
```

![ali-center.png](https://upload-images.jianshu.io/upload_images/11131912-f854f45d0cfb3b11.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

***

##### align-content

`align-content`属性定义了多根轴线的对齐方式。如果项目只有一根轴线，该属性不起作用。

- `flex-start`：与交叉轴的起点对齐。
- `flex-end`：与交叉轴的终点对齐。
- `center`：与交叉轴的中点对齐。
- `space-between`：与交叉轴两端对齐，轴线之间的间隔平均分布。
- `space-around`：每根轴线两侧的间隔都相等。所以，轴线之间的间隔比轴线与边框的间隔大一倍。
- `stretch`（默认值）：轴线占满整个交叉轴。

###### flex-start

```css
.total {
    display: flex;
    flex-flow: row wrap;
    justify-content: flex-start;
    align-content: flex-start;
    height: 500px;
    background: #cccccc
}
```

![ali-con-flex-start.png](https://upload-images.jianshu.io/upload_images/11131912-c630618d1f9c316a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### flex-end

```css
align-content: flex-end;
```

![ali-con-flex-end.png](https://upload-images.jianshu.io/upload_images/11131912-872c9177331f9010.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### center

```css
align-content: center
```

![ali-con-center.png](https://upload-images.jianshu.io/upload_images/11131912-ed275a1dfb9f43e6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### space-between

```css
align-content: space-between
```

![ali-con-space-between.png](https://upload-images.jianshu.io/upload_images/11131912-8feaa7519910bbdb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### space-around

```css
align-content: space-around
```

![ali-con-space-around.png](https://upload-images.jianshu.io/upload_images/11131912-41aa5f7d59a61df9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

###### stretch

```css
align-content: space-around
```

![ali-con-stretch.png](https://upload-images.jianshu.io/upload_images/11131912-dde8f77e879b43c8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

***

#### 项目的属性

- `order`
- `flex-grow`
- `flex-shrink`
- `flex-basis`
- `flex`
- `align-self`

***

##### order

`order`属性定义项目的排列顺序。数值越小，排列越靠前，默认为0。

```css
.box2 {
    background: #555555;
    order: 1;
}
```

![order.png](https://upload-images.jianshu.io/upload_images/11131912-d92c6063e50e39de.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

***

##### flex-grow

`flex-grow`属性定义项目的放大比例，默认为`0`，即如果存在剩余空间，也不放大。前提是有剩余空间。

```css
.box2 {
    background: #555555;
    flex-grow: 0.5;  // 放大为原来的两倍
}
```

![flex-grow.png](https://upload-images.jianshu.io/upload_images/11131912-95dc16c54924c5ef.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

##### flex-shrink

`flex-shrink`属性定义了项目的缩小比例，默认为1，即如果空间不足，该项目将缩小。和上面类似，就不举例子了。前提是空间不足。

##### flex-basis

`flex-basis`属性定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为`auto`，即项目的本来大小。

```css
.box2 {

    background: #555555;

    flex-basis: 200px;

}
```

![flex-basis.png](https://upload-images.jianshu.io/upload_images/11131912-768deb7c446ec08a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

##### flex

`flex`属性是`flex-grow`, `flex-shrink` 和 `flex-basis`的简写，默认值为`0 1 auto`。后两个属性可选。

该属性有两个快捷值：`auto` (`1 1 auto`) 和 none (`0 0 auto`)。

建议优先使用这个属性，而不是单独写三个分离的属性，因为浏览器会推算相关值。

##### align-self

`align-self`属性允许单个项目有与其他项目不一样的对齐方式，可覆盖`align-items`属性。默认值为`auto`，表示继承父元素的`align-items`属性，如果没有父元素，则等同于`stretch`。

```css
// 父元素
.total {
    display: flex;
    flex-flow: row wrap;
    align-items: flex-start;
    height: 300px;
    background: #cccccc
}
// 子元素
.box2 {
    background: #555555;
    align-self: flex-end;
}
```
![align-self.png](https://upload-images.jianshu.io/upload_images/11131912-a7de20b985f9f942.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
***

> 花了半天时间把 Flex 布局梳理了一遍，记忆也更深刻了，这篇 blog 其实感觉就是把阮一峰老师的那篇 copy 了一下，然后自己动手试一下，当然实战中布局不可能这么耿直，更多的还得参考阮一峰老师的实战篇。以后多练习吧。
